Custom items model proposal
CCDirectLink/CLS pull request #7
Opened 2019-05-25 15:26 UTC by 20kdc

Making the "custom-items-model.js" thing more officially

2019-05-29 21:27 UTC, 20kdc commented
NOTE: I might add a further detail in this proposal to make it work better with the patch-steps proposal.
Essentially, the idea behind this would be to allow custom items to be registered from JSON patches.
This solves feature holes in both specifications regarding the registration and usage of a custom item.

2019-05-29 23:27 UTC, 20kdc commented
Actually, ignore that previous note.
The results wouldn't be that beneficial - for one, the item database isn't really suited to JSON patching in any form, and the stuff needed to fix that'd be out of scope for this particular specification.

2019-05-30 22:06 UTC, 2767mr requested changes
I don't know if it's a good idea to accept a proposal that would make saves incompatible with vanille. If a workaround is for that disadvantage, I would be fine with this content of this proposal.

2019-05-30 22:06 UTC, 2767mr commented on proposals/1/custom-items-model.md
> +This is going to cause save compatibility issues.
Please describe the compatibility issues

2019-05-30 22:06 UTC, 2767mr commented on proposals/1/custom-items-model.md
> +- The vanilla game, or modded versions that don't conform to this specification, are likely to crash upon opening the Inventory menu of a save with custom items.
This is a **HUGE** negative. Maybe we should consider workarounds for this case.

2019-05-30 22:06 UTC, 2767mr commented on proposals/1/custom-items-model.md
> +sc.inventory.registerItemAsCustom : function (name, id) : Puts the custom item into the two previous objects.
Please describe the API with the TS declaration syntax

2019-05-30 22:06 UTC, 2767mr commented on proposals/1/custom-items-model.md
> +I recommend `sc.PlayerModel.getSaveData` and `sc.PlayerModel.preLoad` as the functions of choice to wrap.
The author of the spec should not recommend anything in a spec. Either rephrase it or make it a requiremet.

2019-05-30 22:06 UTC, 2767mr commented on proposals/1/custom-items-model.md
> +`getSaveData`'s wrapping is simple - after receiving the resulting object from the parent function, add the key `"customItems"`, as a copy of `sc.inventory.customItemToId`.
"'s wrapping is simple" is subjective and should therefor not go into a spec

2019-05-30 22:06 UTC, 2767mr commented on proposals/1/custom-items-model.md
> +https://github.com/20kdc/CLS-20kdc-Code/tree/master/modules/game/feature/custom-items
Maybe we should move the ref implementation into this repo?

2019-05-30 22:06 UTC, 2767mr commented on proposals/1/custom-items-model.md
> +Note that this doesn't contain the already-injected check.
Maybe rephrase this to be a bit more formal

2019-05-30 22:38 UTC, 20kdc commented
This'll take a while to rewrite to be fully foolproof against breaking Vanilla, and Botanics might stir up some trouble anyway (Turns out drop counts won't be properly handled by the current setup - probably non-fatal but I still need to start checking everything to see where *else* all this data is flowing), so consider this on hold and/or cancelled.

2019-05-30 22:38 UTC, closed without merging